/* ═══════════════════════════════════════════════════════════════
   LHANDLERS WIKI — registry.js  v1.2
   Pour ajouter une page :
     1. Créer pages/mon-id.js  (avec window.PAGES["mon-id"] = `...`)
     2. Ajouter une ligne ici
   La sidebar se génère AUTOMATIQUEMENT depuis ce fichier.
   ═══════════════════════════════════════════════════════════════ */

window.REGISTRY = [
  { id:'home',            title:'Accueil',                  icon:'⌂',  category:'Lhandlers',         keywords:'accueil wiki lhandlers elebellum',                                                                                                        summary:'Page d\'accueil du wiki Lhandlers — accès à toutes les entrées de l\'encyclopédie d\'Elebellum.' },
  { id:'lhandlers',       title:'Lhandlers',                icon:'✦',  category:'Lhandlers',         keywords:'multivers cinema spectateur supreme univers',                                                                                              summary:'Le multivers-cinéma créé par le Spectateur Suprême. Une infinité de mondes projetés sur un écran infini — imperceptible depuis l\'intérieur.' },
  { id:'spectateur',      title:'Spectateur Suprême',       icon:'👁', category:'Lhandlers',         keywords:'spectateur supreme createur lhandlers elus meta imperceptible',                                                                           summary:'Créateur de Lhandlers, il est parmi les spectateurs — pas au-dessus d\'eux. Il se confond avec le public. Aucun personnage ne peut le percevoir.' },

  { id:'cosmologie',      title:'Cosmologie',               icon:'✦',  category:'Cosmologie',        keywords:'cosmologie giatyr tenryobu dieux forces fondamentales desequilibre',                                                                      summary:'Deux forces fondamentales régissent Elebellum : Giatyr et Tenryobu. Ni l\'une ni l\'autre n\'est connue des vivants. Le mal est structurellement plus puissant.' },
  { id:'giatyr',          title:'Giatyr',                   icon:'◎',  category:'Cosmologie',        keywords:'giatyr bien paix creation planete labyrinthe kaio',                                                                                       summary:'Force du bien dans Elebellum. Il existe, mais aucun personnage ne le sait. Reclus sur sa planète hors du temps, il attend que les héros viennent à lui.' },
  { id:'tenryobu',        title:'Tenryobu',                 icon:'◎',  category:'Cosmologie',        keywords:'tenryobu mal guerre destruction murmures impulsions insidieux',                                                                           summary:'Force du mal dans Elebellum. Il n\'ordonne pas — il murmure des idées sombres qui semblent toujours venir de soi-même. Indétectable et structurellement plus fort que Giatyr.' },

  { id:'tunhgoud',        title:'Tunhgoud',                 icon:'◎',  category:'Le Monde',          keywords:'tunhgoud disque iles volantes trou noir boule lumineuse arche cosmique donut climat zones destockar neo garrius',                        summary:'Le Grand Disque — arche cosmique en forme de donut flottant à l\'intérieur du trou noir Destockar. Îles volantes, Néo Garrius au centre, multiples zones climatiques.' },
  { id:'destockar',       title:'Destockar',                icon:'◎',  category:'Le Monde',          keywords:'destockar trou noir tunhgoud singularite neo garrius contenant inconnu especes',                                                         summary:'Le trou noir à l\'intérieur duquel flotte Tunhgoud. Inconnu de toutes les espèces vivantes. Sa singularité — Néo Garrius — a été transformée par les Firigilians.' },
  { id:'neogarrius',      title:'Néo Garrius',              icon:'☀',  category:'Le Monde',          keywords:'neo garrius boule lumineuse singularite destockar bibliotheque firigilians archive universelle teleporteur gargaras soleil tunhgoud',     summary:'La boule lumineuse centrale de Tunhgoud — singularité de Destockar transformée par les Firigilians. Soleil du disque, archive universelle, bibliothèque. Accès via téléporteur enfoui dans Gargaras.' },
  { id:'chronologie',     title:'Chronologie',              icon:'⧗',  category:'Le Monde',          keywords:'chronologie an 0 arrivee humains tunhgoud firigilians atteleck terre histoire',                                                          summary:'L\'An 0 est l\'arrivée de l\'Arch sur Tunhgoud. Tout ce qui précède est histoire ancienne. Tout ce qui suit est l\'histoire d\'Elebellum.' },
  { id:'farkaras',        title:'Farkaras',                 icon:'🌋', category:'Le Monde',          keywords:'farkaras empire farkeyes territoires conquis tunhgoud jarlarkeyes capitale drakarnias sandmen',                                           summary:'L\'empire Farkeyes — tous les territoires conquis dans le disque, gouvernés depuis Drakarnias. Pas de frontières fixes : l\'empire avance.' },
  { id:'drakarnias',      title:'Drakarnias',               icon:'🏚', category:'Le Monde',          keywords:'drakarnias capitale farkaras scioprius volcanique lave chaleur firigilians grottes palais jarlarkeyes volcan technologie heritee',        summary:'Capitale des Farkeyes — île volcanique flottante, ancienne planète Scioprius brûlée par les guerres de pourpalite. Chaleur extrême, lave, ruines Firigilians.' },
  { id:'rignaras',        title:'Rignaras',                 icon:'🏝', category:'Le Monde',          keywords:'rignaras archipel iles volantes lacs zones humides monde natal wargnyr bloodeater pourpalite lune artificielle firigilians',             summary:'Archipel d\'îles volantes aux lacs et zones humides. Monde natal des Wargnyr et des Bloodeater. Ancienne installation Firigilians, lune artificielle en orbite.' },
  { id:'volioce',         title:'Volioce',                  icon:'🌿', category:'Le Monde',          keywords:'volioce archipel iles volantes forets nature yvaans avaans evolution forcee firigilians',                                                summary:'Archipel forestier, berceau des Yvaan\'s et terrain d\'expérimentation Firigilians ayant produit les Avaan\'s par évolution forcée. Nature dense, peu de technologie.' },
  { id:'gargaras',        title:'Gargaras',                 icon:'🏜', category:'Le Monde',          keywords:'gargaras planete desertifiee sandmen pevectus desert oaspring gumbricus triops ruines artefacts teleporteur firigilians neo garrius',    summary:'Planète désertifiée par les Firigilians — berceau des Sandmen. Le désert de Gargaras cache des ruines Pevectus, la salle de cartographie Firigilians, et le téléporteur vers Néo Garrius.' },
  { id:'oaspring',        title:'Oaspring',                 icon:'🌿', category:'Le Monde',          keywords:'oaspring colonie humaine gargaras arch dernier vol oasis commandante mattarial desert',                                                  summary:'Colonie humaine fondée dans le désert de Gargaras autour de l\'Arch reconverti. Berceau de Mattarial. Se développe lentement, dépendante des réserves de l\'Arch.' },

  { id:'firigilians',     title:'Les Firigilians',          icon:'⬡',  category:'Espèces',           keywords:'firigilians pieuvres cyborgs immortels connaissance kardashev disparus genocide pourpalite sang farkeyes elus tunhgoud scioprius protocole halo sans remords', summary:'Pieuvres cyborgs immortelles — première civilisation de Tunhgoud, niveau Kardashev absolu. Disparues. Elles ont créé le disque, exploité les Farkeyes comme bétail, et sont peut-être encore là.' },
  { id:'farkeyes',        title:'Les Farkeyes',             icon:'⬡',  category:'Espèces',           keywords:'farkeyes reptiliens peau rouge conquete ego cicatrices demonite biologique jarlarkeyes omega spartiate mutation pourpalite betail sang scioprius farkaras tresantes lezards', summary:'Reptiliens peau rouge, mutés par la pourpalite. Anciens bétails énergétiques des Firigilians devenus conquérants. Hiérarchie des cicatrices, seule espèce à vouloir dominer Tunhgoud.' },
  { id:'sandmen',         title:'Les Sandmen',              icon:'⬡',  category:'Espèces',           keywords:'sandmen pevectus gargaras nomades caravanes triops gumbricus avidite artefacts piraterie oaspring mattarial survie desert',             summary:'Anciennement Pevectus — désertifiés par les Firigilians pour avoir défié leur autorité. Nomades en caravanes dans le désert de Gargaras, sans structure ni mémoire collective intacte.' },
  { id:'avaans',          title:"Les Avaan's",              icon:'⬡',  category:'Espèces',           keywords:"avaans vayolis atteleck chats humanoïdes nature technologie bouclier zombies trahison elfe cyberpunk",                                    summary:"Chats humanoïdes en deux factions opposées : les Vayolis (nature, forêts) et les Atteleck (technologie, cité sous bouclier). Une trahison a séparé les deux pour toujours." },
  { id:'yvaanspage',      title:"Les Yvaan's",              icon:'⬡',  category:'Espèces',           keywords:"yvaanspage yvaans nature pacifistes arbres ancestres avaans primitif",                                                                    summary:"Ancêtres pacifistes des Avaan's. Communion totale avec la nature, technologie quasi-nulle. Les Firigilians les ont utilisés comme matière première pour créer les Avaan's." },
  { id:'paradeath',       title:'Les Paradeath',            icon:'⬡',  category:'Espèces',           keywords:'paradeath parasites cérébraux contrôle total nuque expérience firigilians echec volioce cerveau tentaculaire',                           summary:'Parasites cérébraux issus d\'une expérience Firigilians ratée. S\'accrochent à la nuque, prennent le contrôle total du cerveau. Incontrôlables, même par leurs créateurs.' },
  { id:'wargnyr',         title:'Les Wargnyr',              icon:'⬡',  category:'Espèces',           keywords:'wargnyr loups humanoïdes rignaras clans dispersés lacs zones humides tunhgoud expérience firigilians',                                   summary:'Loups humanoïdes de Rignaras. Organisés en clans familiaux dispersés sur les îles. Technologie primitive, forte culture orale. Produits par expérimentation Firigilians.' },
  { id:'bloodeater',      title:'Les Bloodeater',           icon:'⬡',  category:'Espèces',           keywords:'bloodeater chauves-souris humanoïdes rignaras chasse nocturne écholocation clans falaises grottes expérience firigilians',               summary:'Chauves-souris humanoïdes de Rignaras. Chasseurs solitaires nocturnes à l\'écholocation développée. Prédateurs naturels des Wargnyr. Vivent dans les falaises et les grottes.' },
  { id:'humains',         title:'Les Humains',              icon:'⬡',  category:'Espèces',           keywords:'humains arch 10000 survivants terre detruite loi reproduction elu bombe sagesse philosophie gingkosa garrius nexios gwemelis oaspring gargaras', summary:'10 000 survivants de la Terre détruite, arrivés sur Tunhgoud à l\'An 0. Fondateurs d\'Oaspring sur Gargaras. Porteurs d\'une philosophie de sagesse forgée dans la catastrophe.' },

  { id:'demonite',        title:'La Demonite',              icon:'◆',  category:'Magie & Pouvoirs',  keywords:'demonite cristal bordeaux sang farkeyes massacre genocide pouvoirs contact vol inerte vivant exception distance biologique pourpalite violet batterie mattarial pendentif', summary:'Cristal bordeaux taillé dans la pourpalite et le sang Farkeyes. Confère des pouvoirs au contact. Batterie d\'énergie quasi-infinie. Le pendentif de Mattarial en est un exemplaire pur.' },
  { id:'elus',            title:'Les Élus',                 icon:'◆',  category:'Magie & Pouvoirs',  keywords:'elus designes spectateur supreme demonite ignorants nature giatyr tenryobu balance gingkosa omega mattarial coldfuseon',                  summary:'Êtres désignés quand le déséquilibre entre Giatyr et Tenryobu dépasse un seuil critique. Ils ignorent leur nature jusqu\'au contact avec une Demonite. Leur pouvoir reflète leur caractère.' },
  { id:'pourpalite',      title:'La Pourpalite',            icon:'◆',  category:'Magie & Pouvoirs',  keywords:'pourpalite cristal violet quasi-incassable energie infinie scioprius firigilians sang farkeyes demonite bordeaux recharge guerre crise mutation platos', summary:'Cristal violet quasi-incassable à énergie quasi-infinie. Source de la Demonite, origine de la mutation Farkeyes. La ressource la plus convoitée de l\'histoire d\'Elebellum.' },

  { id:'jarlarkeyes',     title:'Jarlarkeyes',              icon:'◈',  category:'Personnages',       keywords:'jarlarkeyes chef supreme farkeyes invaincu cicatrices longevite mythique omega pere jenas junma frere evolution combat pouvoir adaptation force', summary:'Chef Suprême Farkeyes, invaincu depuis l\'origine. Figure quasi-mythologique à la longévité inexpliquée. Avance inexorablement pour conquérir Tunhgoud — il n\'y a rien à lui offrir pour qu\'il s\'arrête.' },
  { id:'junma',           title:'Junma',                    icon:'◈',  category:'Personnages',       keywords:'junma frere jarlarkeyes gravite pouvoir non-vivant voyageur jenas omega secret intelligence combat',                                        summary:'Frère aîné de Jarlarkeyes. Maître de la gravité — son pouvoir ne s\'applique qu\'aux objets non-vivants. Voyageur solitaire porteur d\'un secret lié à Jenas et à la naissance d\'Omega.' },
  { id:'omega',           title:'Omega',                    icon:'◈',  category:'Personnages',       keywords:'omega fils jarlarkeyes renegat elu farkeyes allie humains traducteur firigilians trois cicatrices tresantes mutin',                        summary:'Fils de Jarlarkeyes, trois cicatrices, Élu Farkeyes confirmé. A trahi son père après avoir découvert qu\'il était envoyé en mission suicide. Allié des humains, traducteur Firigilians en main.' },
  { id:'mattarial',       title:'Mattarial',                icon:'◈',  category:'Personnages',       keywords:'mattarial elu sandmen manipulation matiere atomique oaspring gargaras pendentif demonite coldfuseon bricoleur crise identitaire pevectus', summary:'Élu Sandmen — seul survivant d\'un massacre, élevé par les humains à Oaspring. Manipule la matière à l\'échelle atomique. Bricoleur, en crise identitaire. Découvreur de ColdFuseon.' },
  { id:'coldfuseon',      title:'ColdFuseon',               icon:'◈',  category:'Personnages',       keywords:'coldfuseon cyborg fusion organique mecanique elu artefact firigilians inconnu inactif gargaras mattarial armes corps',                     summary:'Être partiellement organique, partiellement mécanique — découvert inactif dans une ruine Firigilians sous Gargaras. Élu dont le pouvoir est de modifier son corps en armes. Race et origine inconnues.' },
  { id:'gingkosa',        title:'Gingkosa',                 icon:'◈',  category:'Personnages',       keywords:'gingkosa elu humain premier ne tunhgoud nexios gwemelis demonite inactif',                                                                summary:'Premier humain né sur Tunhgoud, dans Nexios. Élu Humain désigné mais encore inactif — il n\'a pas encore croisé de Demonite. Sa révélation bouleversera une communauté traumatisée par les pouvoirs.' },
  { id:'garrius',         title:'Garrius',                  icon:'◈',  category:'Personnages',       keywords:'garrius arch commandant scientifique upstars loi reproduction 10000 survivants trou de ver',                                              summary:'Scientifique et premier commandant de l\'Arch. A découvert le vaisseau, pas construit. A conduit les 10 000 survivants vers Tunhgoud. Fondateur des Upstars.' },
  { id:'jenas',           title:'Jenas',                    icon:'◈',  category:'Personnages',       keywords:'jenas compagne jarlarkeyes mere omega secret junma farkeyes decedee accouchement',                                                        summary:'Compagne de Jarlarkeyes, mère d\'Omega. Décédée en accouchant. Porte un secret lié à Junma qui remet en question la paternité d\'Omega et change tout ce que Jarlarkeyes croit savoir.' },
  { id:'hope',            title:'Hope Diapearlake',         icon:'◈',  category:'Personnages',       keywords:'hope diapearlake president nations unies traitre destruction terre organisation bombe upstars',                                           summary:'Présidente des Nations Unies. Traître. C\'est elle qui a ordonné la destruction de la Terre — convaincue que c\'était le seul moyen de sauver l\'humanité de quelque chose de pire.' },

  { id:'prologue',        title:'Prologue — Lhandlers',     icon:'❝',  category:'Textes Canoniques', keywords:'prologue texte canonique lhandlers spectateur piano ocean cinema trone',                                                                  summary:'Texte d\'ouverture de Lhandlers. Un être naît du néant, découvre un piano, crée des mondes — puis se voit dans un miroir et devient le Spectateur Suprême.' },
  { id:'intro-elebellum', title:'Introduction Elebellum',   icon:'❝',  category:'Textes Canoniques', keywords:'introduction elebellum giatyr tenryobu elus balance cycle recommence',                                                                   summary:'Texte d\'introduction à Elebellum. Pose le déséquilibre fondamental entre Giatyr et Tenryobu, et l\'inévitabilité du cycle des Élus.' },

  { id:'upstars',         title:'Upstars',                  icon:'◈',  category:'Organisations',     keywords:'upstars soldats elite nations unies missions impossibles terre garrius hope diapearlake',                                                 summary:'Unité d\'élite fondée par Garrius, héritière des Nations Unies. Spécialisée dans les missions impossibles. Seule organisation humaine structurée à l\'arrivée sur Tunhgoud.' },

  { id:'mysteres',        title:'Mystères & Fils Narratifs',icon:'🔒', category:'Méta',              keywords:'mysteres trou noir firigilians arch jarlarkeyes elu humain loi reproduction vayolis trahison bouclier gingkosa destockar neo garrius teleporteur coldfuseon', summary:'Les questions ouvertes de l\'univers : le secret du trou noir, la disparition des Firigilians, l\'origine de l\'Arch, la paternité d\'Omega, ColdFuseon, le téléporteur de Gargaras, et bien d\'autres fils non résolus.' },
];
